# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datax-sdk-protocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64\x61tax-sdk-protocol.proto\x12\x15\x64\x61tax.sdk.protocol.v1\x1a\x1cgoogle/protobuf/struct.proto\"\n\n\x08Settings\"@\n\x0eInitialization\x12.\n\rconfiguration\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"\r\n\x0bNextOptions\">\n\x0bNextMessage\x12\x11\n\treference\x18\x01 \x01(\t\x12\x0e\n\x06stream\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\".\n\x0b\x45mitMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\treference\x18\x02 \x01(\t\"\x0c\n\nEmitResult2\x82\x02\n\x05\x44\x61taX\x12V\n\nInitialize\x12\x1f.datax.sdk.protocol.v1.Settings\x1a%.datax.sdk.protocol.v1.Initialization\"\x00\x12P\n\x04Next\x12\".datax.sdk.protocol.v1.NextOptions\x1a\".datax.sdk.protocol.v1.NextMessage\"\x00\x12O\n\x04\x45mit\x12\".datax.sdk.protocol.v1.EmitMessage\x1a!.datax.sdk.protocol.v1.EmitResult\"\x00\x42,Z*github.com/nla-is/datax-sdk-protocol/v1;v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datax_sdk_protocol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z*github.com/nla-is/datax-sdk-protocol/v1;v1'
  _SETTINGS._serialized_start=81
  _SETTINGS._serialized_end=91
  _INITIALIZATION._serialized_start=93
  _INITIALIZATION._serialized_end=157
  _NEXTOPTIONS._serialized_start=159
  _NEXTOPTIONS._serialized_end=172
  _NEXTMESSAGE._serialized_start=174
  _NEXTMESSAGE._serialized_end=236
  _EMITMESSAGE._serialized_start=238
  _EMITMESSAGE._serialized_end=284
  _EMITRESULT._serialized_start=286
  _EMITRESULT._serialized_end=298
  _DATAX._serialized_start=301
  _DATAX._serialized_end=559
# @@protoc_insertion_point(module_scope)
